### ISSUE TITLE
the version of samtools in /bin maybe to low

### ISSUE THREAD

**Issue by LYC-vio** [BGI-biotools/stLFRsv#1]
Hi, I've encountered the  `samtools: error while loading shared libraries: liblzma.so.0: cannot open shared object file: No such file or directory` error when running LFR-sv

Samtools1.9 uses liblzma.so.5 instead of liblzma.so.0, and removing samtools file from /bin solves this problem (I've already installed samtools 1.9)

**Comment by BGI-biotools** [comment]
thanks for your advice.
samtools in the /bin is only used to read the bam header and index bam. 
So you can replace it by your samtools at will.

by the way, a full liblzma lib make links for liblzma.so.0 and liblzma.so.5 and, as a consequence, I didn't meet this problem.
